# Generated by Django 6.1.1 on 2026-09-25 08:26

import django.db.models.deletion
import life.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='attachment_url',
        ),
        migrations.CreateModel(
            name='MemoryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=life.models._upload_path)),
                ('name', models.CharField(max_length=200)),
                ('size', models.PositiveIntegerField()),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='life.memory')),
            ],
        ),
    ]
